nyc_taxi_emissions:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../emissions.duckdb'
      # path: '../emissionscopy.duckdb' # for testing
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main
